# Generated by Django 4.2.7 on 2023-11-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_table_alter_menu_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Bookingdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='No_of_guests',
            field=models.IntegerField(default=0),
        ),
    ]
