# Generated by Django 4.2.7 on 2023-11-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_booking_bookingdate_alter_booking_no_of_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Bookingdate',
            field=models.DateTimeField(),
        ),
    ]
